### ISSUE TITLE
tab generation fail leads to bot internal error

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/oda-bot#42]
```
2023-12-12 16:39:07,484 ERROR cli  unexpected exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/odabot/cli.py", line 566, in update_workflows
    subprocess.check_output(["kubectl", "exec", #"-it",
  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['kubectl', 'exec', 'deployment/frontend', '-n', 'staging', '--', 'bash', '-c', 'cd /var/www/mmoda; ~/.composer/vendor/bin/drush dre -y mmoda_photoz_euclid']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/odabot/cli.py", line 582, in update_workflows
    workflow_update_status[project['http_url_to_repo']]['stage_failed'] == 'tab'
KeyError: 'stage_failed'
```

**Comment by volodymyrss** [comment]
closed for being stale
